# .github/workflows/hashnode-blog.yml
name: Latest Hashnode Blog Posts
on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: pknerd/hashnode-blog-readme@main
        with:
          HASHNODE_USERNAME: krizzzz
